services:
    david63.emaillist.admin.controller:
        class: david63\emaillist\controller\admin_controller
        arguments:
            - @config
            - @dbal.conn
            - @request
            - @template
            - @user
            - @pagination
            - %core.root_path%
